version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  strapi1:
    build:
      context: ./strapi
    environment:
      - NODE_ENV=development  # Changed to development for easier debugging
      - DATABASE_HOST=your-postgres-host
      - DATABASE_PORT=5432
      - DATABASE_NAME=your-db-name
      - DATABASE_USERNAME=your-username
      - DATABASE_PASSWORD=your-password
      - DATABASE_SSL=true
    volumes:
      - strapi1_data:/app/public/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strapi1.rule=PathPrefix(`/`)"
      - "traefik.http.services.strapi1.loadbalancer.server.port=1337"
    depends_on:
      - traefik
    networks:
      - app-network
    restart: unless-stopped

  strapi2:
    build:
      context: ./strapi
    environment:
      - NODE_ENV=development  # Changed to development for easier debugging
      - DATABASE_HOST=your-postgres-host
      - DATABASE_PORT=5432
      - DATABASE_NAME=your-db-name
      - DATABASE_USERNAME=your-username
      - DATABASE_PASSWORD=your-password
      - DATABASE_SSL=true
    volumes:
      - strapi2_data:/app/public/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strapi2.rule=PathPrefix(`/`)"
      - "traefik.http.services.strapi2.loadbalancer.server.port=1337"
    depends_on:
      - traefik
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  strapi1_data:
  strapi2_data: