version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"  # Default Redis port
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped

  strapi1:
    build:
      context: ./strapi
    environment:
      - NODE_ENV=development
      # Database settings
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=your-postgres-host
      - DATABASE_PORT=5432
      - DATABASE_NAME=your-db-name
      - DATABASE_USERNAME=your-username
      - DATABASE_PASSWORD=your-password
      - DATABASE_SSL=true
      - DATABASE_SSL_CA=/app/ssl/dbcertificate.pem
      - DATABASE_SSL_REJECT_UNAUTHORIZED=false
      - DATABASE_SCHEMA=public
      # Redis settings
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USERNAME=default
      - REDIS_URL=redis://${REDIS_USERNAME}:${REDIS_PASSWORD}@redis:6379
      # Connection pool settings
      - DATABASE_POOL_MIN=2
      - DATABASE_POOL_MAX=10
      - DATABASE_CONNECTION_TIMEOUT=60000
    volumes:
      - strapi1_data:/app/public/uploads
      - ./ssl:/app/ssl:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strapi1.rule=PathPrefix(`/`)"
      - "traefik.http.services.strapi1.loadbalancer.server.port=1337"
    depends_on:
      - traefik
      - redis
    networks:
      - app-network
    restart: unless-stopped

  strapi2:
    build:
      context: ./strapi
    environment:
      - NODE_ENV=development
      # Database settings
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=your-postgres-host
      - DATABASE_PORT=5432
      - DATABASE_NAME=your-db-name
      - DATABASE_USERNAME=your-username
      - DATABASE_PASSWORD=your-password
      - DATABASE_SSL=true
      - DATABASE_SSL_CA=/app/ssl/dbcertificate.pem
      - DATABASE_SSL_REJECT_UNAUTHORIZED=true
      - DATABASE_SCHEMA=public
      # Redis settings
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USERNAME=default
      - REDIS_URL=redis://${REDIS_USERNAME}:${REDIS_PASSWORD}@redis:6379
      # Connection pool settings
      - DATABASE_POOL_MIN=2
      - DATABASE_POOL_MAX=10
      - DATABASE_CONNECTION_TIMEOUT=60000
    volumes:
      - strapi1_data:/app/public/uploads
      - ./ssl:/app/ssl:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strapi2.rule=PathPrefix(`/`)"
      - "traefik.http.services.strapi2.loadbalancer.server.port=1337"
    depends_on:
      - traefik
      - redis
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  strapi1_data:
  strapi2_data:
  redis_data: