version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.traefik.address=:8080
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      # Modified dashboard rule to accept any host
      - "traefik.http.routers.dashboard.rule=PathPrefix(`/dashboard`) || PathPrefix(`/api`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=traefik"

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - redis_data:/data

  strapi1:
    build:
      context: ./strapi
    env_file: 
      - ./strapi/.env
    # environment:
    #   - NODE_ENV=development
    #   - DATABASE_CLIENT=postgres
    #   - DATABASE_SSL=true
    #   - REDIS_HOST=redis
    #   - REDIS_PORT=6379
    #   - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./strapi:/app
      - /app/node_modules
      - strapi1_data:/app/public/uploads
      - ./ssl:/app/ssl:ro
    labels:
      - "traefik.enable=true"
      # Modified rule to accept any host
      - "traefik.http.routers.strapi1.rule=PathPrefix(`/`)"
      - "traefik.http.services.strapi1.loadbalancer.server.port=1337"
      - "traefik.http.middlewares.strapi-stripprefix.stripprefix.prefixes=/"
      - "traefik.http.routers.strapi1.middlewares=strapi-stripprefix"
    depends_on:
      - traefik
      - redis
    networks:
      - app-network
    restart: unless-stopped

  strapi2:
    build:
      context: ./strapi
    env_file: 
      - ./strapi/.env
    # environment:
    #   - NODE_ENV=development
    #   - DATABASE_CLIENT=postgres
    #   - DATABASE_SSL=true
    #   - REDIS_HOST=redis
    #   - REDIS_PORT=6379
    #   - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./strapi:/app
      - /app/node_modules
      - strapi2_data:/app/public/uploads
      - ./ssl:/app/ssl:ro
    labels:
      - "traefik.enable=true"
      # Modified rule to accept any host
      - "traefik.http.routers.strapi2.rule=PathPrefix(`/`)"
      - "traefik.http.services.strapi2.loadbalancer.server.port=1337"
      - "traefik.http.middlewares.strapi-stripprefix.stripprefix.prefixes=/"
      - "traefik.http.routers.strapi2.middlewares=strapi-stripprefix"
    depends_on:
      - traefik
      - redis
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  strapi1_data:
  strapi2_data:
  redis_data: