services:
  traefik:
    image: traefik:v2.10
    command:
      - --log.level=INFO
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=app-network
      - --entrypoints.web.address=:80
      - --entrypoints.traefik.address=:8080
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=traefik"
    restart: unless-stopped

  strapi1:
    build:
      context: ./strapi
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./strapi/.env
    environment:
      NODE_ENV: production
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/src:/opt/app/src
      - ./strapi/package.json:/opt/app/package.json
      - ./strapi/yarn.lock:/opt/app/yarn.lock
      - strapi1_data:/opt/app/public/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=app-network"
      - "traefik.http.routers.strapi1.rule=PathPrefix(`/`)"
      - "traefik.http.routers.strapi1.entrypoints=web"
      - "traefik.http.services.strapi1.loadbalancer.server.port=1337"
    networks:
      - app-network
    depends_on:
      - traefik
      - redis
      - meilisearch

  strapi2:
    build:
      context: ./strapi
      dockerfile: Dockerfile
    env_file: ./strapi/.env
    environment:
      NODE_ENV: production
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/src:/opt/app/src
      - ./strapi/package.json:/opt/app/package.json
      - ./strapi/yarn.lock:/opt/app/yarn.lock
      - strapi2_data:/opt/app/public/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=app-network"
      - "traefik.http.routers.strapi2.rule=PathPrefix(`/`)"
      - "traefik.http.routers.strapi2.entrypoints=web"
      - "traefik.http.services.strapi2.loadbalancer.server.port=1337"
    networks:
      - app-network
    depends_on:
      - traefik
      - redis
      - meilisearch
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - app-network
    volumes:
      - redis_data:/data
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-STRAPI_UNIVDATOS_SEARCH}
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=production
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - app-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meilisearch.rule=PathPrefix(`/meili`)"
      - "traefik.http.services.meilisearch.loadbalancer.server.port=7700"

networks:
  app-network:
    driver: bridge

volumes:
  strapi1_data:
  strapi2_data:
  redis_data:
  meilisearch_data: