services:
  traefik:
    image: traefik:v2.10
    command:
      - --log.level=INFO
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=app-network
      - --entrypoints.web.address=:80
      - --entrypoints.traefik.address=:8080
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=traefik"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - app-network
    volumes:
      - redis_data:/data
    restart: unless-stopped

  strapi1:
    build:
      context: ./strapi
    env_file: 
      - ./strapi/.env
    # environment:
    #   - NODE_ENV=development
    #   - HOST=0.0.0.0
    #   - PORT=1337
    #   - DATABASE_CLIENT=postgres
    #   - DATABASE_HOST=${DATABASE_HOST}
    #   - DATABASE_PORT=${DATABASE_PORT}
    #   - DATABASE_NAME=${DATABASE_NAME}
    #   - DATABASE_USERNAME=${DATABASE_USERNAME}
    #   - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    #   - DATABASE_SSL=true
    #   - DATABASE_SSL_REJECT_UNAUTHORIZED=false
    #   - REDIS_HOST=redis
    #   - REDIS_PORT=6379
    #   - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./strapi:/app
      - /app/node_modules
      - strapi1_data:/app/public/uploads
      - ./ssl:/app/ssl:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strapi1.rule=PathPrefix(`/`)"
      - "traefik.http.services.strapi1.loadbalancer.server.port=1337"
    depends_on:
      - traefik
      - redis
    networks:
      - app-network
    restart: unless-stopped

  strapi2:
    build:
      context: ./strapi
    env_file: 
      - ./strapi/.env
    # environment:
      # - NODE_ENV=development
      # - HOST=0.0.0.0
      # - PORT=1337
      # - DATABASE_CLIENT=postgres
      # - DATABASE_HOST=${DATABASE_HOST}
      # - DATABASE_PORT=${DATABASE_PORT}
      # - DATABASE_NAME=${DATABASE_NAME}
      # - DATABASE_USERNAME=${DATABASE_USERNAME}
      # - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      # - DATABASE_SSL=true
      # - DATABASE_SSL_REJECT_UNAUTHORIZED=false
      # - REDIS_HOST=redis
      # - REDIS_PORT=6379
      # - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./strapi:/app
      - /app/node_modules
      - strapi2_data:/app/public/uploads
      - ./ssl:/app/ssl:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strapi2.rule=PathPrefix(`/`)"
      - "traefik.http.services.strapi2.loadbalancer.server.port=1337"
    depends_on:
      - traefik
      - redis
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  strapi1_data:
  strapi2_data:
  redis_data: