/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor5 from "@_sh/strapi-plugin-ckeditor/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiAdvancedUuid from "strapi-advanced-uuid/strapi-admin";
import generateData from "strapi-plugin-generate-data/strapi-admin";
import importExportEntries from "strapi-plugin-import-export-entries/strapi-admin";
import meilisearch from "strapi-plugin-meilisearch/strapi-admin";
import menus from "strapi-plugin-menus/strapi-admin";
import multiSelect from "strapi-plugin-multi-select/strapi-admin";
import restCache from "strapi-plugin-rest-cache/strapi-admin";
import translate from "strapi-plugin-translate/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    ckeditor5: ckeditor5,
    "strapi-cloud": strapiCloud,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    "strapi-advanced-uuid": strapiAdvancedUuid,
    "generate-data": generateData,
    "import-export-entries": importExportEntries,
    meilisearch: meilisearch,
    menus: menus,
    "multi-select": multiSelect,
    "rest-cache": restCache,
    translate: translate,
  },
});
